---
# tasks file for base

- name: Install list of packages
  apt: 
    pkg: "{{ item }}" 
    state: installed 
    update_cache: true
  with_items: "{{ packages}}"

- name: network interfaces file configuration
  template:
    src: interfaces.j2
    dest: '/tmp/interfaces.conf' 
    owner: root
    group: root
