galaxy_info:
  author: Jorge Soares
  description: oCloud nextcloud role
  company: oCloud.cz
  license: BSD
  min_ansible_version: 2.4
  github_branch: master
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

dependencies:
  - { role: base }